### ISSUE TITLE
Page lost on edit and save

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#10]
After editing and publishing the page(Quality of Life), got a page not found error. I'm able to see the page title in content section but does not have the edit or delete functionality enabled on the far right....see image below.

![image](https://f.cloud.github.com/assets/2806493/1210054/d9cd5168-25f3-11e3-8e97-66c2509f1562.png)

**Comment by VennilaCity** [comment]
Lost one more page (Arts and Culture)

![image](https://f.cloud.github.com/assets/2806493/1210084/60f67f7a-25f4-11e3-8db8-daa85f65947e.png)

**Comment by VennilaCity** [comment]
Can these node IDs be cleared, so I can add new pages for the two deleted english pages(306021 and 306017)

**Comment by VennilaCity** [comment]
The alias is in use and so I'm unable to create a new page with same URL/name.

**Comment by AaronByrne** [comment]
Dave can you assist with this

@DaveBagler

**Comment by DaveBagler** [comment]
Try now, I just killed the URL alias for it.

**Comment by VennilaCity** [comment]
Still get the error

![image](https://f.cloud.github.com/assets/2806493/1228043/00d0816c-279e-11e3-9123-94ade23a7cc9.png)

**Comment by minorOffense** [comment]
@VennilaCity you can go here and clear out the old link aliases if they're in your way: https://staging.ottawa.ca/en/admin/config/search/path

Just search for the path and then delete the alias.

**Comment by VennilaCity** [comment]
Dave deleted the aliases but the page title still appears in gateway summary?

**Comment by minorOffense** [comment]
Does the node still exist?

**Comment by VennilaCity** [comment]
No it doesn't

![image](https://f.cloud.github.com/assets/2806493/1239468/2231804a-29fb-11e3-81b4-392768fcc4e1.png)

**Comment by VennilaCity** [comment]
The title of the lost page still exists in the node summaries and since a limit of 5 is set, an actual page 'Portrait of Ottawa' is hidden.

![image](https://f.cloud.github.com/assets/2806493/1252977/49f35cc0-2b59-11e3-99ec-3b346849eac7.png)

**Comment by minorOffense** [comment]
I was just cleaning those up. Check again.

**Comment by VennilaCity** [comment]
Looks good. Thanks!
