### ISSUE TITLE
Banner slideshow needs to be added to the portal landing page

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#12]
Immigration portal landing page slideshow of banners have to be added.

**Comment by minorOffense** [comment]
I found some sample images and added them to the page.

You can edit the nodes or create new ones called "Slide" in the node type list.

**Comment by minorOffense** [comment]
Sorry it took me so long. Had a minor emergency to deal with last night.

**Comment by VennilaCity** [comment]
We will need a pause button for the slider.When a title and URL was added to the slide, the link seems to work but the title did not appear and the title background does not seem to have sufficient contrast.

**Comment by VennilaCity** [comment]
Is there a limit to number of slides?
@minorOffense @AaronByrne

**Comment by VennilaCity** [comment]
I have edited the view to accommodate 5 banners, but is there a specific size for the image being used or can it be formatted to display certain size?

**Comment by tiffanytse** [comment]
It will fit any image you put in, however for consistency sake - it's best to have them already cropped all to have the same size before uploading. @VennilaCity

**Comment by VennilaCity** [comment]
When a title and URL was added to the slide, the link seems to work but the title did not appear and the title background does not seem to have sufficient contrast.

**Comment by tiffanytse** [comment]
The links should appear now based on the title of the slide / however I still need to style it :) @VennilaCity 

Make sure to link Sample Image 3, when there is no link included the image / caption will not be linked.

**Comment by VennilaCity** [comment]
Any update on the styling?

**Comment by tiffanytse** [comment]
Should be up and running now :) @VennilaCity

**Comment by tiffanytse** [comment]
Commit d31f0dae3a0a4c8d9c4a0d9d4d76652dcd728583

**Comment by VennilaCity** [comment]
Banner title translation doesn't seem to work. All slides have been translated but I only see English on the french side.

**Comment by tiffanytse** [comment]
I'll make a new issue for that.

**Comment by tiffanytse** [comment]
Actually I think it might have been a cache-ing issue. Seems to be fixed now?

**Comment by VennilaCity** [comment]
Now the french title is showing up in the English side
