### ISSUE TITLE
A page redirect required

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#14]
Client wants a page under 'After you Arrive' gateway called 'Life in Ottawa' which simply needs to redirect to 'Portrait of Ottawa' page under 'Why Choose Ottawa' gateway.

**Comment by minorOffense** [comment]
You can configure redirects here: https://staging.ottawa.ca/en/admin/config/search/redirect

**Comment by VennilaCity** [comment]
In that case will I be able to get a node summary with an image?

**Comment by minorOffense** [comment]
I don't see how a node summary is related to a redirect?

**Comment by VennilaCity** [comment]
Sorry this is not required anymore... I just added another topic to have the page display under two sections.
