### ISSUE TITLE
All section tiltes styled as H3 instead of H2

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#18]
Is there a reason why all the section titles in any page are styled as H3 ? When I switch to H2, they seem to pick up the color scheme of the page, shouldn't they all be H2 then?

**Comment by tiffanytse** [comment]
H2s in the mockups were coloured like H1s. @VennilaCity

**Comment by VennilaCity** [comment]
So is it OK for me to go ahead and switch all H3 to H2?

**Comment by tiffanytse** [comment]
Can you send me a screenshot of what you are trying to edit? I am not sure
what you are referring to .

On Tue, Oct 1, 2013 at 10:19 AM, VennilaCity notifications@github.comwrote:

> So is it OK for me to go ahead and switch all H3 to H2?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/18#issuecomment-25453288
> .

## 

Tiffany Tse

Creative Director
Coldfront Labs Inc.
ttse@coldfrontlabs.ca
twitter: @tiffany_tse

**Comment by VennilaCity** [comment]
![image](https://f.cloud.github.com/assets/2806493/1246928/1946d4b2-2ab4-11e3-8f16-ada0e8847b22.png)

The section titles are not coloured as they are H3s, so I'm wondering if I can change them to H2s so they pick up the color theme just like the H1.

**Comment by tiffanytse** [comment]
Yep, change them to h2's if you want them to look like the mockups (coloured titles)

**Comment by VennilaCity** [comment]
Done.
