### ISSUE TITLE
Titles need bolding

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#19]
Please have all the headings bolded to better identify the sections.

**Comment by tiffanytse** [comment]
They weren't bolded in the mockups - this would be an enhancement.

On Tue, Oct 1, 2013 at 10:54 AM, VennilaCity notifications@github.comwrote:

> Please have all the headings bolded to better identify the sections.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/19
> .

## 

Tiffany Tse

Creative Director
Coldfront Labs Inc.
ttse@coldfrontlabs.ca
twitter: @tiffany_tse
