### ISSUE TITLE
TOC links jumps to wrong item

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#20]
When a section in a page is too small, the TOC highlighted link seems to jump to the next item down in the list.

For ex: http://staging.ottawa.ca/en/immigration/after-you-arrive/how-i-got-settled#sect6

In the above link sect 6 as per URL is Settlement program but the next TOC link Community and Employment Support is highlighted.

This occurs all through the site.

**Comment by tiffanytse** [comment]
This should be fixed; 

https://github.com/CityofOttawa/ottawa_panelized_page_nav/commit/a97220df0981860a328204c188090f18d391e307
