### ISSUE TITLE
Translate links on blocks on the gateway pages

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#21]
The 6 blocks in the portal homepage needs to link to the corresponding gateway pages.

**Comment by VennilaCity** [comment]
Can this and issue #13 be done ASAP, cause the site is being presented to the Mayor tomorrow I believe.

@AaronByrne @minorOffense @elcazador

**Comment by minorOffense** [comment]
Ok.

## 

Mathew Winstone

On Oct 1, 2013, at 13:15, "VennilaCity" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can this and issue #13https://github.com/CityofOttawa/immigration_zen/issues/13 be done ASAP, cause the site is being presented to the Mayor tomorrow I believe.

@AaronByrnehttps://github.com/AaronByrne @minorOffensehttps://github.com/minorOffense @elcazadorhttps://github.com/elcazador

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/21#issuecomment-25469876.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by minorOffense** [comment]
Just a note, the links will only work in english until we add translations. Once these are converted to beans though you won't have to translate link paths as such.

**Comment by VennilaCity** [comment]
'Living/engaging box need to be renamed to just 'Living'

**Comment by elcazador** [comment]
These types of changes will not be completed on a piecemeal basis. Who is requesting these.

**Comment by VennilaCity** [comment]
That's fine. I just thought the gateway navigation was different from the boxes and took a suggestion from the client.

**Comment by VennilaCity** [comment]
All six blocks on the French home page link to english pages.

**Comment by minorOffense** [comment]
Do we have the links yet? I tried getting Drupal to auto-load the french version of the given paths in english but that didn't work. I have to set them with a conditional in the page template (once again, only until we have the beans in place).

**Comment by VennilaCity** [comment]
It should be as below:

Pourquoi choisir Ottawa - https://staging.ottawa.ca/fr/immigration/pourquoi-choisir-ottawa
Avant votre arrivée - https://staging.ottawa.ca/fr/immigration/avant-votre-arrivee
Après votre arrivée - https://staging.ottawa.ca/fr/immigration/apres-votre-arrivee
Travail et affaires - https://staging.ottawa.ca/fr/immigration/travail-et-affaires
Étudier - https://staging.ottawa.ca/fr/immigration/etudiants-etrangers
Vivre - https://staging.ottawa.ca/fr/immigration/vivre

**Comment by VennilaCity** [comment]
@minorOffense @elcazador 

The links need to be fixed.

**Comment by minorOffense** [comment]
Done.
