### ISSUE TITLE
Background colors mixed up within gateways

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#22]
Working/Doing Business has grey background which is for International Students gateway. Living has green background while it should be blue..and such

**Comment by VennilaCity** [comment]
French gateway of Working/Doing business has the wrong background color

http://staging.ottawa.ca/fr/immigration/travail-et-affaires

**Comment by tiffanytse** [comment]
@minorOffense correct body class needs to be added to this page for it to work `.immigration-business`

**Comment by tiffanytse** [comment]
This should be fixed now; updated context paths.
