### ISSUE TITLE
Background image not aligned

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#23]
The city hall image in the background on the bottom left has a small vertical gap to the actual page, need to align properly.

**Comment by VennilaCity** [comment]
The grey Ottawa address block at the bottom needs aligning with the page on the right as well....clearly visible in this URL

https://staging.ottawa.ca/en/immigration/after-you-arrive

**Comment by tiffanytse** [comment]
Not sure what you mean. Can you screenshot?

**Comment by VennilaCity** [comment]
![image](https://f.cloud.github.com/assets/2806493/1253915/3d18c6fc-2b6d-11e3-8244-66c885296202.png)

**Comment by tiffanytse** [comment]
Hmm - it might be just the size of the bg's that were sent are off by a few pixels - let me see if I can fudge it with css.

**Comment by tiffanytse** [comment]
Should be fixed now.

**Comment by VennilaCity** [comment]
Thanks...looks good!

**Comment by VennilaCity** [comment]
Can the background image of parliament and city hall just made to stay in the window and only the page scroll?

**Comment by tiffanytse** [comment]
Can you create a new issue for that @VennilaCity

**Comment by VennilaCity** [comment]
Sure no problem.
