### ISSUE TITLE
Infinite loop page error

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#29]
Under why choose Ottawa, went to page Arts and Culture and then toggled to french and got this error. Page not found error in IE.

![image](https://f.cloud.github.com/assets/2806493/1345481/663df844-3690-11e3-9edc-894c8664e9f8.png)

**Comment by VennilaCity** [comment]
@minorOffense  Any thoughts on why this is happening....this page can't be viewed at all in IE

**Comment by minorOffense** [comment]
My guess would be someone added a redirect for the node which is redirecting back to itself. But without a link I can't check.

Check at the bottom of the node edit form and remove any redirects which are set on the node. That should help. (both french and english).

**Comment by VennilaCity** [comment]
Thanks...removed the redirect and is fine now.
