### ISSUE TITLE
Remove h3 and h4 from TOC

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#31]
Configure Table of contents to only display h2 headings and not h3 and h4.

**Comment by VennilaCity** [comment]
This needs to be fixed before tomorrow as well

**Comment by minorOffense** [comment]
This is a code change to the module Dave wrote.

**Comment by VennilaCity** [comment]
@DaveBagler

**Comment by VennilaCity** [comment]
@AaronByrne @DaveBagler 

Any update?

**Comment by DaveBagler** [comment]
See Issue #39.
