### ISSUE TITLE
Immigration logo needs to be added ASAP

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#32]
Add logo to the portal before the site is supposedly being circulated tomorrow.

**Comment by minorOffense** [comment]
Can you post the logo here? I can't find it in my email.

**Comment by VennilaCity** [comment]
![image](https://f.cloud.github.com/assets/2806493/1354224/289580d6-3751-11e3-9736-fddca9b90c04.png)

**Comment by VennilaCity** [comment]
![image](https://f.cloud.github.com/assets/2806493/1354227/360d2610-3751-11e3-92f8-1abcdc9b73a1.png)

**Comment by VennilaCity** [comment]
I'll email the images to you too.

**Comment by tiffanytse** [comment]
Fixed bb95faec115f5535391c262461d608aec4826e3e

Font substitute for translation is this one, since the fonts they chosen are not websafe. 
http://www.google.com/fonts/specimen/Balthazar
