### ISSUE TITLE
Translation of slideshow captions not working

### ISSUE THREAD

**Issue by tiffanytse** [CityofOttawa/immigration_zen#33]
French side of site doesn't translate slideshow titles properly.

**Comment by tiffanytse** [comment]
Actually I think it might have been a cache-ing issue. Seems to be fixed now? @VennilaCity

**Comment by tiffanytse** [comment]
French is on english side now.

**Comment by VennilaCity** [comment]
Looks fine now...maybe just the cache

**Comment by minorOffense** [comment]
We fixed the view. Added an explicit check for language (for some reason the normal language detection was failing for the title field)
