### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#34]
https://staging.ottawa.ca/en/immigration/after-you-arrive/getting-settled-ottawa

Page does not load. Jephtee was editing the page and when she tried to save, she got the alert that the page has been modified by another user and on refresh the page wouldn't load anymore. It's simply blank.

**Comment by VennilaCity** [comment]
@AaronByrne @minorOffense

**Comment by minorOffense** [comment]
Node was corrupted. I've deleted the node. Please recreate.

**Comment by VennilaCity** [comment]
I recreated the page and it looked fine but when Jephtee made edits to it and saved, again it's not leading.

@minorOffense @elcazador

**Comment by minorOffense** [comment]
I've disabled the toc on that page and restored the content. Something with the wysiwyg editor is creating markup that's making the DOMDocument object actions break.

If you don't make any edits the page should remain functional until we figure out what's up with the ToC generator (or replace it with Dave's in house proper one).
