### ISSUE TITLE
Update picture on home page

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#35]
Replace 'Before you Arrive' picture in home page block with this. Will email you the image as well.

![image](https://f.cloud.github.com/assets/2806493/1362113/171c8134-3813-11e3-8f86-c7a9796d0085.png)

**Comment by tiffanytse** [comment]
I will have to crop this picture significantly for it to fit; the luggage will probably be cropped if you want to see the faces. @VennilaCity

**Comment by VennilaCity** [comment]
Or you can use this
![image](https://f.cloud.github.com/assets/2806493/1372808/5bf88234-3a58-11e3-8639-7b126ae48eab.png)

**Comment by tiffanytse** [comment]
I'll put the ladies up first
you can see if you like it, if not, then we can switch it again. @VennilaCity

**Comment by tiffanytse** [comment]
The new image is up @VennilaCity

**Comment by VennilaCity** [comment]
Will confirm with client and get back on this.

**Comment by VennilaCity** [comment]
Client is happy with the ladies picture.
