### ISSUE TITLE
Home page edits

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#36]
The text that appears when you pass over the section boxes:
a) Why Choose Ottawa (note that Choose is capitalized and shouldn’t be if it is following the sentence case rule)

Change the message to:  “See what Ottawa has to offer.”

b) Before you arrive: 

Change the message to: “A practical guide to preparing for life in Ottawa.”

c) After you arrive:

Change the message to: “A practical guide to adapting to life in Ottawa.”

d) On the top navigation menu, change “International students” to “Learning” to match the boxes menu

e) There are words in the banner.  These are not legible. I checked and it is a browser issue. It’s displaying okay on Chrome but not IE. 

f) boxes on the home page of the French version are not link properly. When I click on them, it takes me to the English site instead of the French site.

@minorOffense

**Comment by VennilaCity** [comment]
@tiffanytse 

Above are not the titles to the boxes on the home page, they are the text that appears when you pass over the section boxes.

**Comment by AaronByrne** [comment]
Can these changes be made ASAP so that @VennilaCity and send the site out for review?

@minorOffense @tiffanytse

**Comment by minorOffense** [comment]
This is the text from that Word doc.

```
1. There are words in the banner.  These are not legible. 
I checked and it is a browser issue. It’s displaying okay on Chrome but not IE. 

2. The text that appears when you pass over the section boxes:
a) Why Choose Ottawa (note that Choose is capitalized and shouldn’t be if it is following the sentence case rule)
Change the message to:  “See what Ottawa has to offer.”

b) Before you arrive: 
Change the message to: “A practical guide to preparing for life in Ottawa.”

C) After you arrive:
Change the message to: “A practical guide to adapting to life in Ottawa.”

D) On the top navigation menu, change “International students” to “Learning” to match the boxes menu
------------------------------
For the french
2 a) Change the message to:  « Découvrez tout ce qu’Ottawa a à offrir. »
B) Change the message to:  « Un guide pratique pour vous préparer à vivre à Ottawa. »
C) Change the message to:  « Un guide pratique pour s'adapter à la vie à Ottawa. »
D) On the top navigation menu and the boxes, change “Étudiants Étrangers” to “Étudier” to match English version


```

**Comment by minorOffense** [comment]
Updated the text in english.
1. d) Changing the menu text is a setting change to the menus. Vennila you should be able to do that.

The text has been updated and is ready for translation. Using the translation client should work now.

Do you have the links for the french side? I have to translate then manually in code.

**Comment by VennilaCity** [comment]
Translations are in now. But the six blocks on the french homepage don't link to the right sections.

**Comment by minorOffense** [comment]
Right, I don't have the links :-S

Or if I do, I have misplaced them...

**Comment by minorOffense** [comment]
See #21

**Comment by VennilaCity** [comment]
Alt text for the six blocks show the old text, needs to be updated to the new edited text.

**Comment by minorOffense** [comment]
I just updated the text to what was sent to me via email. See my comment above.

If that's the wrong text then someone will have to provide me with the new one.

**Comment by minorOffense** [comment]
Alright I'll change that.

## 

Mathew Winstone

On Oct 25, 2013, at 14:27, "VennilaCity" <notifications@github.com<mailto:notifications@github.com>> wrote:

Reopened #36https://github.com/CityofOttawa/immigration_zen/issues/36.

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/36.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by minorOffense** [comment]
So just so we're clear, the same text that's visible in the paragraphs as the alt text in the images in each box correct?

**Comment by VennilaCity** [comment]
That's correct.
