### ISSUE TITLE
Banner text background missing

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#41]
Home page banners missing the background color for the text in IE

**Comment by minorOffense** [comment]
Can you specify which version of IE?

**Comment by VennilaCity** [comment]
IE 8

**Comment by VennilaCity** [comment]
![image](https://f.cloud.github.com/assets/2806493/1419888/9193a6f8-3fd5-11e3-91fe-600d166ea714.png)
