### ISSUE TITLE
Update logo font in Header

### ISSUE THREAD

**Issue by AaronByrne** [CityofOttawa/immigration_zen#42]
@minorOffense 
Matt I just sent you an email with the ai files, they have a new font for the "Welcoming, Diverse, Vibrant" text in the header
@VennilaCity

**Comment by minorOffense** [comment]
Is it a web font?

**Comment by AaronByrne** [comment]
I don't know I don't have ai so I can't see it...

**Comment by tiffanytse** [comment]
Can you post the ai file to here? @AaronByrne

**Comment by tiffanytse** [comment]
That didn't really work @AaronByrne

**Comment by AaronByrne** [comment]
I couldn't figure out another way... Send me your email and I'll forward them.

Sent using my iPhone.

On 2013-10-28, at 12:59 PM, "Tiffany Tse" <notifications@github.com<mailto:notifications@github.com>> wrote:

That didn't really work @AaronByrnehttps://github.com/AaronByrne

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/42#issuecomment-27231224.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by minorOffense** [comment]
Has that been resolved yet? Did they pick a font?

**Comment by tiffanytse** [comment]
The font in the ai file was 'expanded to outlines' so I can't check what it is, I think it's Myriad Pro (but that is an adobe font, and not websafe. A font needs to be chosen from http://google.com/fonts, and I would suggest Open Sans or something similar to what they have already chosen. @AaronByrne @minorOffense
