### ISSUE TITLE
Adjust min-height of boxes on home page to match even when single line of text

### ISSUE THREAD

**Issue by minorOffense** [CityofOttawa/immigration_zen#43]
The text on the home page for "why choose ottawa" is lower than the rest since they shortened the display text.

We should adjust the boxes to always have the same min height value.

**Comment by tiffanytse** [comment]
Its not quite that easy; a min height messes with the animation - I did fix it by adding a break though;

**Comment by tiffanytse** [comment]
Nevermind, I found a way to fix it using min-height on the paragraph instead;

**Comment by webstandards** [comment]
@tiffanytse a bit better, but still out of alignment with the one-liners next to it in IE8+. If this is the best we can do then so be it I guess.
![ie_alignment](https://f.cloud.github.com/assets/4095270/1424151/88a226ee-4018-11e3-90d1-0314c28d8e6d.jpg)
