### ISSUE TITLE
IE8: Aliasing on text is jagged

### ISSUE THREAD

**Issue by webstandards** [CityofOttawa/immigration_zen#44]
Wasn't sure how much of an issue this was as we can't expect perfection in old IEs and this is an IE8 and lower issue, Aaron says 'it needs to be fixed but not a high priority'.

The mouseover effect on text in the sub-sections is causing horribly grainy text in IE8. Can the text effect simply be removed if <=IE8?

![ie8_uglytext](https://f.cloud.github.com/assets/4095270/1423995/8802250c-4015-11e3-8f54-7406c3d11c19.jpg)

**Comment by webstandards** [comment]
Forgot to FYI @elcazador @AaronByrne @minorOffense

**Comment by tiffanytse** [comment]
The font color changes; this is an ie rendering issue (for whatever reason IE can't antialias fonts correctly) - has nothing to do with content, there needs to be a hover indication so it should stay @webstandards .

**Comment by webstandards** [comment]
@tiffanytse the client is not me it's Aaron did you ask the client what he want to do before closing the ticket?  'IE can't antialias fonts correctly' we know is the problem we're looking for a solution please. If the tradeoff is no hover indicator on the text in IE8 (I see other hover indicators on the mouse and arrow indicator) this is an acceptable tradeoff to me versus almost illegible text - but I am not the client, find out what is acceptable to @AaronByrne 

If a hover indicator on the text is required, you could apply an underline or a background color change in <= IE8 instead could you not? There is always a solution. Unfortunately our corporate standard is IE8 so we can't just ignore it and have something unprofessional looking. Again from Aaron ''it needs to be fixed but not a high priority'
