### ISSUE TITLE
IE8: Carousel indicator not working

### ISSUE THREAD

**Issue by webstandards** [CityofOttawa/immigration_zen#45]
Another 'low priority but we should make it work' from Aaron:

The 5 squares/circles 'indicator' below the carousel is not working at all in IE8, fine in IE10+. Seems completely dead, does not indicate which carousel item you're on, nor can you click to another item.

@AaronByrne @elcazador

**Comment by minorOffense** [comment]
Yup, seems to be a bug between FlexSlider and IE8/9. Looking into it.
