### ISSUE TITLE
Carousel Pause Button

### ISSUE THREAD

**Issue by webstandards** [CityofOttawa/immigration_zen#46]
@AaronByrne requested I open a ticket to request the carousel should have a pause button. Hopefully this is a configurable item?

@elcazador pls don't shoot the messenger, I am but a lonely humble servant boy.

**Comment by minorOffense** [comment]
It does. Just needs to be turned on.

**Comment by minorOffense** [comment]
Going to turn on and then style it. I'll position it just like the hope page slider (I'll also move the pager controls up to match)

**Comment by AaronByrne** [comment]
Hi Tiffany can you move the controls below the slider or into the shaded regio at the bottom of the slider

with them inside the image we run in to accessibility issues (Contrast)

**Comment by AaronByrne** [comment]
Also with this setup in IE 8 when you click on the buttons that should load the different sliders it opens the page the slider links to rather than moving the slider.

**Comment by tiffanytse** [comment]
No problem; will do @AaronByrne

**Comment by tiffanytse** [comment]
Not sure why that is happening in IE8 but @minorOffense or myself will investigate too

**Comment by minorOffense** [comment]
@AaronByrne can you draw it up quickly to show us where?

**Comment by minorOffense** [comment]
@AaronByrne  As a side note, if you're going to run into accessibility issues with the positioning here, then it would be safe to assume the same issue would apply to the current home page.

Edit:

Acutally there is no accessibility issue here. It's not text or anything you're trying to show. The links are available as keyboard shortcuts and to screen readers. Their visibility levels aren't an accessibility issue as far as compliance is concerned.

**Comment by AaronByrne** [comment]
It's a good point that we should fix the homepage slider as well. Sometimes I can't see the buttons. Accessibility isn't just for screen readers and keyboard nav.

Can we you style so that the controls are at the bottom like the following link:

http://ottawa.ca/en/city-hall/get-know-your-city/improving-your-neighbourhood/neighbourhood-connection-office

also can we reduce the overall size of the banner scale it so that the ouside edges align with the mid points of the first and last nav items.

(the left edge would allign with the middle of the Why chose Ottawa box above it.)

**Comment by tiffanytse** [comment]
I have aligned the slider the way you requested, however I think it looks a bit strange just because everything else, on the landing page, and even on other pages throughout the site is aligned to the edges of the buttons. If you do want it changed back, let me know. @AaronByrne

**Comment by tiffanytse** [comment]
One suggestion to make the slider not as tall, would be to change the dimensions, and upload landscape type photos, ones that are cropped and significantly shorter (400px height by 900px width). This would allow for the slider to be shorter in height, but still fit within the rest of the page.
