### ISSUE TITLE
Footer and header links

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#47]
Please add the below links to the footer bottom
1. ottawa.ca linking to http://ottawa.ca/en (English)
   ottawa.ca linking to http://ottawa.ca/fr (French)
2. Browse Aloud linking to http://ottawa.ca/en/node/297165 (English)
   Naviguer à haute voix linking to http://ottawa.ca/fr/node/297166 (French)

Corrected links to the already existing items in footer provided below
1. Disclaimer - http://ottawa.ca/en/node/297163 (En)
   Avertissement - http://ottawa.ca/en/node/297164 (Fr)
2. Privacy - http://ottawa.ca/en/node/297161 (En)
   Confidentialité - http://ottawa.ca/en/node/297162 (Fr)
3. Accessibility - http://ottawa.ca/en/node/268378 (En)
   Accessibilité - http://ottawa.ca/en/node/274656 (Fr)

Add Contact us link to the header.
1. Contact Us - http://ottawa.ca/en/ taxonomy/term/3207 (En)
   Nous joindre - http://ottawa.ca/fr/ taxonomy/term/3207 (Fr)

**Comment by AaronByrne** [comment]
2 new requirements for the upper part of the footer: (can this be a block that I can edit? I think we just add it immediately to the left of the ottawa logo)

1)Add the Province of Ontario logo: please place on the 
![ontario_logo](https://f.cloud.github.com/assets/2185125/1522425/a6757adc-4ba7-11e3-92d4-df9a5b9438e9.png)
![ontariologo](https://f.cloud.github.com/assets/2185125/1522426/a67f184e-4ba7-11e3-8aaa-1ed6a05dbf75.png)

2)Add the Social media icons and links that are in the Ottawa.ca footer on the right.

3)I may have to add an email address and phone number though I am trying to negotiate my way out of that... it would go with the address.

if this was a content area I'd just do it myself :/

**Comment by tiffanytse** [comment]
I think it would look best if we kept everything centered for now; just in terms of design - since there is nothing to balance out the footer on the left hand side. But I am adding them in right now. @AaronByrne

**Comment by tiffanytse** [comment]
@VennilaCity the menu is set up now for you to add in all the links you need to.

**Comment by tiffanytse** [comment]
@VennilaCity @AaronByrne Contact menu has been added to header area, and styled (bdb4a6ff077da21ada0d506cc255e75e391db1de)
