### ISSUE TITLE
FRENCH HOMEPAGE is missing

### ISSUE THREAD

**Issue by AaronByrne** [CityofOttawa/immigration_zen#49]
the French landing page ottawa.ca/fr/immigration has nothing on it...

@minorOffense @DaveBagler @tiffanytse @elcazador

**Comment by AaronByrne** [comment]
the header and footer are there but nothing in the body

**Comment by minorOffense** [comment]
That’s odd…

## Let me have a look.

Mathew Winstone
mathew.winstone@ottawa.camailto:mathew.winstone@ottawa.ca

On Nov 14, 2013, at 5:39 PM, AaronByrne <notifications@github.com<mailto:notifications@github.com>> wrote:

the French landing page ottawa.ca/fr/immigrationhttp://ottawa.ca/fr/immigration has nothing on it...

@minorOffensehttps://github.com/minorOffense @DaveBaglerhttps://github.com/DaveBagler @tiffanytsehttps://github.com/tiffanytse @elcazadorhttps://github.com/elcazador

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/49.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by AaronByrne** [comment]
and the English:

Diverse. Welcoming. Vibrant. is ni english rather than French

**Comment by minorOffense** [comment]
The french page was being taken over by the translation of a taxonomy term in french. Removing the alias has fixed that.

The translation text for that page needs to be applied using the translation toolbar at the bottom.

**Comment by minorOffense** [comment]
I can try to export the translations from staging, give me a minute...

**Comment by minorOffense** [comment]
How's that? The translations seemed to import pretty well.

ottawa.ca/fr/immigration

**Comment by minorOffense** [comment]
I'll be away from my computer for a bit but everything in french looks good. Feel free to reopen if you found anything else.
