### ISSUE TITLE
home page in IE missing colours for menu and also for the boxes.

### ISSUE THREAD

**Issue by AaronByrne** [CityofOttawa/immigration_zen#51]
Matt, what would it take to fix this tonight? big job or no? 

if it was just the menus that would be one thing but the boxes look super broken.

**Comment by minorOffense** [comment]
This is a regression issue from the changes we made to the ToC the other day.

I can't fix it tonight as I would require access to write files to production.

We can fix it first thing in the morning.

**Comment by AaronByrne** [comment]
Ok. Had to ask.

**Comment by AaronByrne** [comment]
@minorOffense any progress finding the issue?

**Comment by minorOffense** [comment]
@citychanri 

```
git clone --branch 7.x-1.x http://git.drupal.org/project/selectivizr.git /var/www/html/drupal/sites/all/modules/contrib/selectivizr
wget http://selectivizr.com/downloads/selectivizr-1.0.2.zip --no-check-certificate
unzip selectivizr-1.0.2.zip
mv selectivizr-1.0.2 /var/www/html/drupal/sites/all/libraries/selectivizr
drush en selectivizr -y -l ottawa.ca --root=/var/www/html/drupal
```
