### ISSUE TITLE
Embedded videos show up twice

### ISSUE THREAD

**Issue by pdesourdy** [CityofOttawa/immigration_zen#52]
When embedding a video using the "Insert/Edit Embedded Media" tool in the WYSIWYG editor 
![image](https://f.cloud.github.com/assets/2789366/1552865/cff2a0bc-4e2a-11e3-8d98-5de15e6299dd.png) the video shows up twice. I didn't have any problems embedding videos on a regular ottawa.ca page.

I'm trying to embed 2 videos on this page: https://ottawa.ca/en/immigration/working-and-doing-business/finding-job

And it ends up looking like this:

![image](https://f.cloud.github.com/assets/2789366/1552883/1f5c5fee-4e2b-11e3-8469-8ccfb532c457.png)

@AaronByrne @minorOffense

**Comment by minorOffense** [comment]
I don't see any duplicate videos on that page. Can you try the content out on staging to see what it looks like?

**Comment by AaronByrne** [comment]
We removed the video because the site is live and it looked broken.

**Comment by AaronByrne** [comment]
didn't mean to close.

**Comment by pdesourdy** [comment]
Check it out:
https://staging.ottawa.ca/en/immigration/working-and-doing-business/finding-job

The second one shows up when you hover your mouse over the big white space...

Note and observation:
1. Ottawa.ca prod - videos do not play in IE8, videos do not show up twice
2. Immigration staging - videos do play in IE8, videos show up twice

**Comment by pdesourdy** [comment]
bringing in @VennilaCity and @DaveBagler to help out

**Comment by pdesourdy** [comment]
@minorOffense Any luck? Is there a better video player that we should be using for playing local media like videos?

**Comment by DaveBagler** [comment]
So the wet video player wont work because we are not using wet within the immigration section.

**Comment by AaronByrne** [comment]
Ok, that seems logical.

Is there another player we can use?

Sent using my iPhone.

On 2013-11-20, at 11:17 AM, "Dave Bagler" <notifications@github.com<mailto:notifications@github.com>> wrote:

So the wet video player wont work because we are not using wet within the immigration section.

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/52#issuecomment-28903067.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by pdesourdy** [comment]
Have you used this one before @DaveBagler https://drupal.org/project/cck_video ?

**Comment by tiffanytse** [comment]
Was this fixed? @DaveBagler @AaronByrne

**Comment by tylerpepper** [comment]
@minorOffense I've been asked to look into this, and heard that you may have a solution (a new video player or something that you already have working?) Thanks.

**Comment by minorOffense** [comment]
As part of another project, we’re building out some video player stuff for the city. No code written yet. Bagler and I have to work on it in the coming months.

If you can fix the existing bug in wetkit go for it. But I wouldn’t spend too much time reimplementing anything yet. (Unless someone tells you to do so specifically)

## 

Mathew Winstone
mathew.winstone@ottawa.camailto:mathew.winstone@ottawa.ca

On Jan 14, 2014, at 9:03 AM, tylerpepper <notifications@github.com<mailto:notifications@github.com>> wrote:

@minorOffensehttps://github.com/minorOffense I've been asked to look into this, and heard that you may have a solution (a new video player or something that you already have working?) Thanks.

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/52#issuecomment-32266499.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by AaronByrne** [comment]
I need a fix one way or another in the next week or so. Whether it's a different player of a fix to the wet bug. The client for immigration has been patient but that is wearing thin.

**Comment by pdesourdy** [comment]
Any updates on this? @AaronByrne wanted this fixed a couple weeks ago. The client for immigration is getting frustrated.

**Comment by minorOffense** [comment]
Nothing yet. I'm working on cleaning the capital, Bagler was temporarily banned from the office and Tyler is doing youth portal.

So now time allotted to creating the player.

## 

Mathew Winstone

On Feb 5, 2014, at 12:02, "Phil Desourdy" <notifications@github.com<mailto:notifications@github.com>> wrote:

Any updates on this? @AaronByrnehttps://github.com/AaronByrne wanted this fixed a couple weeks ago. The client for immigration is getting frustrated.

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/52#issuecomment-34210670.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Comment by AaronByrne** [comment]
my understanding is that @tylerpepper and @DaveBagler have this worked out when can the new player be deployed to prod?

**Comment by DaveBagler** [comment]
Yeah, you just need to put in the mark-up but @tylerpepper or I can send you the markup to use.

**Comment by pdesourdy** [comment]
@DaveBagler The new video player is working properly. Below is the code for embedding videos

`<p><video id="HR1" class="video-js vjs-default-skin ottawa-vjs-skin vjs-big-play-centered" controls preload="none" width="auto" height="auto" data-setup="{}">
<source src="http://ottawa.ca/include/immigration/03_HR1 v2 en.mp4" type='video/mp4' />
</video></p>`
