### ISSUE TITLE
Empty H2 causing empty ToC

### ISSUE THREAD

**Issue by minorOffense** [CityofOttawa/immigration_zen#53]
http://ottawa.ca/en/immigration/working-and-doing-business/finding-job#toc_h2_2

Be sure whatever content you have there has valid H2 content

@AaronByrne @pdesourdy @VennilaCity

**Comment by AaronByrne** [comment]
so I got rid of the H2 wrapping the youtube video... now the ToC is gone from the page?

**Comment by AaronByrne** [comment]
Changed text format back to WYSIWYG and it's back!
