### ISSUE TITLE
Image caption alignment issue

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#54]
Captions seem not to wrap around image properly leaving a margin. 

http://ottawa.ca/fr/immigration/travail-et-affaires/lancer-une-entreprise#toc_h2_8

It's the CSS
# main img {

margin: 1em 2em;
}

**Comment by tiffanytse** [comment]
Sorry this content-type was not in the original mockups, so I didn't style for it. I will fix this up tomorrow morning. :sunny: @VennilaCity
