### ISSUE TITLE
Titles on landing pages need to be sentence case

### ISSUE THREAD

**Issue by DaveBagler** [CityofOttawa/immigration_zen#56]
I know it isn't proper English but the titles on the landing pages of immigration need to be in sentence case so:

<code>Before You Arrive</code>

should be:

<code>Before you arrive</code>

The capitalization is being forced in the CSS.

**Comment by alanOTT** [comment]
I was taught to capitalize all major words in titles of books, articles, film, etc. So the first example would be correct. See http://www.psc-cfp.gc.ca/abt-aps/stgd-gdst/index-eng.htm#toc2.3.  Is there another reason sentence case is required?

**Comment by gibbardra** [comment]
Corporate standard is sentence casing unless it is a proper name. So second example is correct.

**Comment by AaronByrne** [comment]
this issues isn't resolved. is it waiting to be pushed? 

i.e. from prod, look at the title of this page: https://ottawa.ca/en/immigration/why-choose-ottawa 

@DaveBagler @tiffanytse

**Comment by tiffanytse** [comment]
The changes to the theme just need to be pulled onto prod; its already been pushed from qa to the theme repository. @AaronByrne
