### ISSUE TITLE
New nodes require grouping

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#57]
@minorOffense @AaronByrne @DaveBagler 

Client is requesting adding more nodes under the 'learning' gateway and needs grouping of the nodes with new titles as they are listed under the gateway.

Currently the gateway has

![image](https://cloud.githubusercontent.com/assets/2806493/3219021/315df230-eff1-11e3-9a30-287b8f2f6920.png)

Client is looking to add

![image](https://cloud.githubusercontent.com/assets/2806493/3219018/1cb3cb98-eff1-11e3-8094-a914229dad10.png)

![image](https://cloud.githubusercontent.com/assets/2806493/3219023/3dc137ee-eff1-11e3-9051-48301066cc31.png)

![image](https://cloud.githubusercontent.com/assets/2806493/3219025/41c96dc0-eff1-11e3-86c7-0078f92a9a83.png)

**Comment by VennilaCity** [comment]
@AaronByrne Can this be done? The client has the pages ready as drafts to be published. Can the requirement be achieved?

**Comment by AaronByrne** [comment]
@VennilaCity This should be added as 3 new pages in the Learning section.

**Comment by VennilaCity** [comment]
https://ottawa.ca/fr/immigration/etudier

Please change the color theming to match the gateway color of grey
