### ISSUE TITLE
French side of Immigration completely missing the gateway navigation bar

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#7]
French side of Immigration needs the navigation links and also the 6 blocks in the portal landing page are still in English.

The pages need to be styled like English, currently they look as in the screenshot below.

![image](https://f.cloud.github.com/assets/2806493/1182497/63909472-221c-11e3-8393-9574578fca05.png)

**Comment by minorOffense** [comment]
What URL do you get when you switch to french? The theme switch is entirely driven by the URL path.

**Comment by VennilaCity** [comment]
Sorry, forgot to update that I had gone in and translated all the taxonomies and the path for it to work.
