### ISSUE TITLE
Issues with page summaries

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#9]
Some of the page summaries are split up into multiple paragraphs as in the links below https://staging.ottawa.ca/en/immigration/international-students
https://staging.ottawa.ca/en/immigration/why-choose-ottawa

Wondering if Max summary limit is 4, as some gateways have 5 pages and only 4 summaries show up.

Testing page summary can be removed to accomodate pages.

**Comment by minorOffense** [comment]
Yup. It is set to show 4.

You can delete the test content page if you like.

**Comment by minorOffense** [comment]
Do you want to show 5 instead?

**Comment by VennilaCity** [comment]
I have modified the view to display 5 items. Thanks.

**Comment by VennilaCity** [comment]
But still does not display 5 items...is it because of the summary splitting up into many paragraphs here https://staging.ottawa.ca/en/immigration/international-students ?

**Comment by minorOffense** [comment]
Check to make sure the content you've created meets the Views filtering criteria. (i.e. requires an image, published, etc...)

**Comment by VennilaCity** [comment]
Yes it does meet all the criteria

**Comment by VennilaCity** [comment]
Mathew, did you have a chance to look into this as the portal is being to showed to the Mayor next week?

@minorOffense @elcazador

**Comment by AaronByrne** [comment]
@VennilaCity can you confirm if this is working correctly now?

**Comment by VennilaCity** [comment]
Nope not yet...

https://staging.ottawa.ca/en/immigration/international-students

**Comment by minorOffense** [comment]
I've fixed the weird whitespace issue. (there was a stray link tag in the content). I've updated the filters to disallow links in the summaries.

Colours are being worked on now.

**Comment by minorOffense** [comment]
see #15 for colour switching updates.

**Comment by tiffanytse** [comment]
Fixed issue; make sure to have summary content as paragraphs though for best results (lists don't display as nicely).
